[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "22"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "https://your-production-api-url.com"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://your-staging-api-url.com"
